from typing import Literal
from pydantic import BaseModel

from app.utils.constants import OPEN_AI_KEY


class ToolModel(BaseModel):
    id: str
    name: str
    type: str
    gpt_model: str
    llm: str
    description: str
    what_i_do: str
    category: str
    state: str
    require_key: bool
    key_name: str | None
    input_type: Literal["none", "string", "url", "pdf", "image", "object"]
    object_schema: str | None
    ui_loading_message:str
    ui_loaded_message:str
    ui_loaded_message_error:str


tools_data: dict[str, ToolModel] = {
    "684a054b6c981a601e166627": ToolModel(
        id="684a054b6c981a601e166627",
        name="Classify Message",
        type="classify_message",
        gpt_model="gpt-4.1-nano",
        llm=OPEN_AI_KEY,
        description="To classify next node type based on prompt",
        what_i_do="Check if the provided prompt satisfies this type 'classify_message' if yes return type as 'classify_message' else ignore",
        category="generate",
        state="active",
        require_key=True,
        key_name=OPEN_AI_KEY,
        input_type="none",
        object_schema=None,
  ui_loading_message = "Preparing the next tool...",
ui_loaded_message = "Classification completed.",
ui_loaded_message_error = "Failed to select the next tool."

    ),
    "684a08e28f7c63eb043302d1": ToolModel(
        id="684a08e28f7c63eb043302d1",
        name="Evaluate Code",
        type="evaluate_code",
        gpt_model="gpt-4.1-mini",
        llm=OPEN_AI_KEY,
        description="Used to evaluate code generated by llm model.",
        what_i_do="Check if the provided prompt satisfies this type 'evaluate_code' if yes return type as 'evaluate_code' else ignore",
        category="generate",
        state="active",
        require_key=True,
        key_name=OPEN_AI_KEY,
        input_type="none",
        object_schema=None,
 ui_loading_message = "Evaluating code...",
ui_loaded_message = "Code evaluation completed.",
ui_loaded_message_error = "Failed to evaluate code."

    ),
    "684a0a2a14df3de4f4f6845d": ToolModel(
        id="684a0a2a14df3de4f4f6845d",
        name="General Text",
        type="write_message",
        gpt_model="gpt-4.1-mini",
        llm=OPEN_AI_KEY,
        description="Used to generate text based on prompt provided by user.",
        what_i_do="Check if the provided prompt satisfies this type 'write_message' if yes return type as 'write_message' else Ignore",
        category="generate",
        state="active",
        require_key=True,
        key_name=OPEN_AI_KEY,
        input_type="none",
        object_schema=None,
 ui_loading_message = "Generating text...",
ui_loaded_message = "Text generation completed.",
ui_loaded_message_error = "Failed to generate text."

    ),
    "684a0afa8e798279e19a3e6d": ToolModel(
        id="684a0afa8e798279e19a3e6d",
        name="Send Mail",
        type="send_mail",
        gpt_model="",
        llm="",
        description="beta: To send mail to the recipient based on prompt provided by user.",
        what_i_do="Check if the provided prompt satisfies this type 'write_mail_and_send' if yes return type as 'write_mail_and_send' else Ignore",
        category="action",
        state="inactive",
        require_key=True,
        key_name="gmail",
        input_type="none",
        object_schema=None,
ui_loading_message = "Sending email...",
ui_loaded_message = "Email sent successfully.",
ui_loaded_message_error = "Failed to send email."

    ),
    "684a0c5df84f78f814367574": ToolModel(
        id="684a0c5df84f78f814367574",
        name="Write Code",
        type="write_code",
        gpt_model="gpt-4.1",
        llm=OPEN_AI_KEY,
        description="To write code based on the prompt provided by the user.",
        what_i_do="Check if the provided prompt satisfies this type 'write_code' if yes return type as 'write_code' else ignore",
        category="generate",
        state="active",
        require_key=True,
        key_name=OPEN_AI_KEY,
        input_type="none",
        object_schema=None,
ui_loading_message = "Generating code...",
ui_loaded_message_error = "Code generation failed.",
ui_loaded_message = "Code generated successfully!"

    ),
    "684d858808dca10a34a65a53": ToolModel(
        id="684d858808dca10a34a65a53",
        name="On Prompt",
        type="on_prompt",
        gpt_model="",
        llm="",
        description="Run on receiving prompt.",
        what_i_do="",
        category="initiate",
        state="active",
        require_key=False,
        key_name=None,
        input_type="none",
        object_schema=None,
ui_loading_message = "Setting up the graph...",
ui_loaded_message_error = "Setup failed to start.",
ui_loaded_message = "Graph setup completed successfully!"

    ),
    "686a060b7493977b931934c3": ToolModel(
        id="686a060b7493977b931934c3",
        name="On Start",
        type="on_start",
        gpt_model="",
        llm="",
        description="Run flow on initiate no input required.",
        what_i_do="",
        category="initiate",
        state="active",
        require_key=False,
        key_name=None,
        input_type="none",
        object_schema=None,
        ui_loading_message = "Setting up the graph...",
ui_loaded_message_error = "Failed to start setup.",
ui_loaded_message = "Setup completed successfully!"

    ),
    "684d8a5608dca10a34a65a55": ToolModel(
        id="684d8a5608dca10a34a65a55",
        name="Conditional Routing",
        type="conditional_routing",
        gpt_model="",
        llm="",
        description="Used to route the user to different nodes based on the provided types.",
        what_i_do="",
        category="conditional",
        state="active",
        require_key=False,
        key_name=None,
        input_type="none",
        object_schema=None,
ui_loading_message = "Redirecting to the tool...",
ui_loaded_message_error = "Redirection failed.",
ui_loaded_message = "Successfully redirected to the tool!"

    ),
    "684e733dc2b59ec01fb72c77": ToolModel(
        id="684e733dc2b59ec01fb72c77",
        name="End",
        type="end",
        gpt_model="",
        llm="",
        description="Finish flow.",
        what_i_do="",
        category="close",
        state="active",
        require_key=False,
        key_name=None,
        input_type="none",
        object_schema=None,
ui_loading_message = "Finalizing the flow...",
ui_loaded_message_error = "An error occurred while finishing the flow.",
ui_loaded_message = "Flow finalized successfully!"

    ),
    "6853a91c8ed701f2efcd6fd1": ToolModel(
        id="6853a91c8ed701f2efcd6fd1",
        name="Code Documentation",
        type="code_documentation",
        gpt_model="gpt-4.1-nano",
        llm=OPEN_AI_KEY,
        description="To create documentation of provided code, response will be in markdown file",
        what_i_do="Check if the provided prompt is an code and satisfies or requested this type 'code_documentation' if yes return type as 'code_documentation' else ignore",
        category="generate",
        state="active",
        require_key=True,
        key_name=OPEN_AI_KEY,
        input_type="none",
        object_schema=None,
        ui_loading_message = "Generating code documentation...",
ui_loaded_message_error = "Failed to generate code documentation.",
ui_loaded_message = "Code documentation completed successfully!"

    ),
    "6853c80d8ed701f2efcd6fd2": ToolModel(
        id="6853c80d8ed701f2efcd6fd2",
        name="HTML/Markdown to PDF",
        type="doc_to_pdf",
        gpt_model="",
        llm="",
        description="To convert any HTML or Markdown file to pdf.",
        what_i_do="To convert any HTML or Markdown file to pdf.",
        category="generate",
        state="active",
        require_key=False,
        key_name="",
        input_type="none",
        object_schema=None,
ui_loading_message = "Preparing your PDF document...",
ui_loaded_message_error = "Oops! Something went wrong during conversion.",
ui_loaded_message = "PDF converted successfully!"

    ),
    "68585eca3aa24f736ddb2a59": ToolModel(
        id="68585eca3aa24f736ddb2a59",
        name="Text Search Tavily",
        type="tavily_search",
        gpt_model="",
        llm="",
        description="Use tavily as search engine for text",
        what_i_do="To search user text search query on tavily search",
        category="action",
        state="active",
        require_key=True,
        key_name="tavily",
        input_type="string",
        object_schema=None,
     ui_loading_message = "Searching...",
ui_loaded_message_error = "Oops! Something went wrong during the search.",
ui_loaded_message = "Search completed successfully!"

    ),
    "6866c9cf9f3b944d6d0f9935": ToolModel(
        id="6866c9cf9f3b944d6d0f9935",
        name="Script Writer",
        type="script_writer",
        gpt_model="gpt-4.1-mini",
        llm=OPEN_AI_KEY,
        description="Write Professionals Script for any provided content.",
        what_i_do="Check if the provided prompt satisfies this type 'script_writer' if yes return type as 'script_writer' else ignore",
        category="generate",
        state="active",
        require_key=True,
        key_name=OPEN_AI_KEY,
        input_type="none",
        object_schema=None,
     ui_loading_message = "Writing your script...",
ui_loaded_message_error = "Oops! Something went wrong while generating the script.",
ui_loaded_message = "Script completed successfully!"

    ),
    "686915a6acd2b4a126714ec3": ToolModel(
        id="686915a6acd2b4a126714ec3",
        name="Google Trends",
        type="google_trend",
        gpt_model="",
        llm="",
        description="Find top trending topic on google trend and make full use out of it. More tools coming soon in this family...",
        what_i_do="Check if the provided prompt satisfies this type 'google_trend' if yes return type as 'google_trend' else ignore this tool google_trend can help user to find trends on google as per there need",
        category="action",
        state="active",
        require_key=False,
        key_name="",
        input_type="none",
        object_schema=None,
ui_loading_message = "Scanning for the latest trends...",
ui_loaded_message_error = "Oops! Couldn't fetch the trends.",
ui_loaded_message = "Here's the top trend we found!",

    ),
    "68761d62027f5fe62f9c7fdd": ToolModel(
        id="68761d62027f5fe62f9c7fdd",
        name="On Speech",
        type="on_speech",
        gpt_model="whisper-1",
        llm=OPEN_AI_KEY,
        description = "Convert user audio into text and pass it to the next...",
        what_i_do="Check if the provided prompt satisfies this type 'on_speech' if yes return type as 'on_speech' else ignore this tool.",
        state="active",
        category="initiate",
        require_key=True,
        key_name=OPEN_AI_KEY,
        input_type="none",
        object_schema=None,
        ui_loading_message = "Listening...",
        ui_loaded_message_error = "Sorry, I didn't catch that.",
        ui_loaded_message = "Got it!",
    ),
      "686a027e7493977b931934c2": ToolModel(
        id="686a027e7493977b931934c2",
        name="Create Tweet",
        type="create_tweet",
        gpt_model="gpt-4.1",
        llm=OPEN_AI_KEY,
        description="Write/Generate tweet based on provided data in prompt or based on past response.",
        what_i_do="Check if the provided prompt satisfies this type 'create_tweet' if yes return type as 'create_tweet' else ignore this tool, create_tweet can help user to generate tweet based on past meta or response",
        category="generate",
        state="active",
        require_key=True,
        key_name=OPEN_AI_KEY,
        input_type="none",
        object_schema=None,
        ui_loading_message = "Preparing tweet...",
ui_loaded_message_error = "Failed to generate tweet.",
ui_loaded_message = "Tweet successfully generated."
    ),
}
