from pydantic import BaseModel


class ToolModel(BaseModel):
    id: str
    name: str
    type: str
    gpt_model: str
    llm: str
    description: str
    what_i_do: str
    category: str
    state: str


tools_data: dict[str, ToolModel] = {
    "684a054b6c981a601e166627": ToolModel(
        id="684a054b6c981a601e166627",
        name="Classify Message",
        type="classify_message",
        gpt_model="gpt-4.1-nano",
        llm="openai",
        description="To classify next node type based on prompt",
        what_i_do="Check if the provided prompt satisfies this type 'classify_message' if yes return type as 'classify_message' else ignore",
        category="generate",
        state="active",
    ),
    "684a08e28f7c63eb043302d1": ToolModel(
        id="684a08e28f7c63eb043302d1",
        name="Evaluate Code",
        type="evaluate_code",
        gpt_model="gpt-4.1-mini",
        llm="openai",
        description="Used to evaluate code generated by llm model.",
        what_i_do="Check if the provided prompt satisfies this type 'evaluate_code' if yes return type as 'evaluate_code' else ignore",
        category="generate",
        state="active",
    ),
    "684a0a2a14df3de4f4f6845d": ToolModel(
        id="684a0a2a14df3de4f4f6845d",
        name="General Text",
        type="write_message",
        gpt_model="gpt-4.1-mini",
        llm="openai",
        description="Used to generate text based on prompt provided by user.",
        what_i_do="Check if the provided prompt satisfies this type 'write_message' if yes return type as 'write_message' else Ignore",
        category="generate",
        state="active",
    ),
    "684a0afa8e798279e19a3e6d": ToolModel(
        id="684a0afa8e798279e19a3e6d",
        name="Send Mail",
        type="send_mail",
        gpt_model="gpt-4.1-mini",
        llm="openai",
        description="beta: To send mail to the recipient based on prompt provided by user.",
        what_i_do="Check if the provided prompt satisfies this type 'write_mail_and_send' if yes return type as 'write_mail_and_send' else Ignore",
        category="action",
        state="inactive",
    ),
    "684a0c5df84f78f814367574": ToolModel(
        id="684a0c5df84f78f814367574",
        name="Write Code",
        type="write_code",
        gpt_model="gpt-4.1",
        llm="openai",
        description="To write code based on the prompt provided by the user.",
        what_i_do="Check if the provided prompt satisfies this type 'write_code' if yes return type as 'write_code' else ignore",
        category="generate",
        state="active",
    ),
    "684d858808dca10a34a65a53": ToolModel(
        id="684d858808dca10a34a65a53",
        name="On Prompt",
        type="on_prompt",
        gpt_model="gpt-4.1-nano",
        llm="openai",
        description="Run on receiving prompt.",
        what_i_do="",
        category="initiate",
        state="active",
    ),
    "684d8a5608dca10a34a65a55": ToolModel(
        id="684d8a5608dca10a34a65a55",
        name="Conditional Routing",
        type="conditional_routing",
        gpt_model="gpt-4.1-nano",
        llm="openai",
        description="Used to route the user to different nodes based on the provided types.",
        what_i_do="",
        category="conditional",
        state="active",
    ),
    "684e733dc2b59ec01fb72c77": ToolModel(
        id="684e733dc2b59ec01fb72c77",
        name="End",
        type="end",
        gpt_model="gpt-4.1-nano",
        llm="openai",
        description="Finish flow.",
        what_i_do="",
        category="close",
        state="active",
    ),
    "6853a91c8ed701f2efcd6fd1": ToolModel(
        id="6853a91c8ed701f2efcd6fd1",
        name="Code Documentation",
        type="code_documentation",
        gpt_model="gpt-4.1-nano",
        llm="openai",
        description="To create documentation of provided code, response will be in markdown file",
        what_i_do="Check if the provided prompt is an code and satisfies or requested this type 'code_documentation' if yes return type as 'code_documentation' else ignore",
        category="generate",
        state="active",
    ),
    "6853c80d8ed701f2efcd6fd2": ToolModel(
        id="6853c80d8ed701f2efcd6fd2",
        name="HTML/Markdown to PDF",
        type="doc_to_pdf",
        gpt_model="gpt-4.1-nano",
        llm="openai",
        description="To convert any HTML or Markdown file to pdf.",
        what_i_do="To convert any HTML or Markdown file to pdf.",
        category="generate",
        state="active",
    ),
    "68585eca3aa24f736ddb2a59": ToolModel(
        id="68585eca3aa24f736ddb2a59",
        name="Text Search Tavily",
        type="tavily_search",
        gpt_model="gpt-4.1-nano",
        llm="openai",
        description="User tavily as search engin for text",
        what_i_do="To search user text search query on tavily search",
        category="action",
        state="active",
    ),
    "6866c9cf9f3b944d6d0f9935": ToolModel(
        id="6866c9cf9f3b944d6d0f9935",
        name="Script Writer",
        type="script_writer",
        gpt_model="gpt-4.1-nano",
        llm="openai",
        description="Write Professionals Script fo any provided content.",
        what_i_do="Check if the provided prompt satisfies this type 'script_writer' if yes return type as 'script_writer' else ignore",
        category="generate",
        state="active",
    ),
}
